### ISSUE TITLE
Possible errors

### ISSUE THREAD

**Issue by jeffa00** [audstanley/NodeJs-Raspberry-Pi#1]
First of all, I want to say thanks for this script. You saved me much hair pulling.

I ran into a couple of issues with the node install bits (I didn't need mongo, so I just manually ran the node install).

First was this line:

sudo mv node-v5.3.0-linux-armv7l.tar.gz/ /opt/nodejs/;

I'm pretty sure you meant this:

sudo mv node-v5.3.0-linux-armv7l/ /opt/nodejs/;

Second were the symlinks.

It didn't work for me until I added this link:

sudo ln -s /opt/nodejs/bin/node /usr/local/bin/node

Other than that it worked like a charm, and I thank you once more!

**Comment by audstanley** [comment]
Thank you so much!  I'll fix this right away. :+1: 
update applied,and fixed. :smile:

**Comment by m4recek** [comment]
One more possible issue. move of node can fail if there is a node installed already, same goes for symlinks.

And two suggestion, sorry I don't have time for PR's now :)
1. You can change script to support both version of arm. You can check supported arm version by running `cat /proc/cpuinfo` so if `cat /proc/cpuinfo | grep ARMv6` returns something then install arm6 version. I had to manually copy and change line by line because of it :/
2. Would be awesome if you can add mongodb as optional. Saves quite a lot of time. 

Oh, and... awesome work! :+1:

**Comment by audstanley** [comment]
Thanks!  I didn't really think about a second install issue.  I'll defiantly fix that, and I appreciate the ARM6 check.  I've got some older Pi's so that'll save me some time too.  I agree, that the mongo should be optional.  I might have to add some params like -n for node and -m for mongo, and -nm  for both.
