### ISSUE TITLE
Installation hangs up my Pi 3 with Stretch

### ISSUE THREAD

**Issue by ba58smith** [audstanley/NodeJs-Raspberry-Pi#18]
When I run the "wget" line, a lot happens in a hurry, then the cursor hangs up, and I have to Ctrl+C to get out:
```
wget -O - https://raw.githubusercontent.com/audstanley/NodeJs-Raspberry-Pi/master/Install-Node.sh | sudo bash
--2018-07-24 18:43:24--  https://raw.githubusercontent.com/audstanley/NodeJs-Raspberry-Pi/master/Install-Node.sh
[sudo] password for butch: Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.4.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.4.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1689 (1.6K) [text/plain]
Saving to: 'STDOUT'

-                           100%[===========================================>]   1.65K  --.-KB/s    in 0s      

2018-07-24 18:43:25 (28.3 MB/s) - written to stdout [1689/1689]
```
I've done it twice, same result. After Ctrl+C, I try to run "node -v", and get:
-bash: node: command not found

Did I miss a step?

**Comment by audstanley** [comment]
There are a few things that needs to be installed, try it again, wait like 10 minutes.  ~~It's slow because of some of the pip installs needed...~~ like the requests library, which allows the node-install utility to be able to query the node distribution page **directly** for the latest installs (needed for future upgrades).

First install is the longest (it's a slow raspberry pi after all), and then when you run the sudo node-install -v 8     (or which ever version), than it should run fast as long as you don't have too many gloabal node modules installed (on a fresh install, you wont).  it's nice to have the version switching for upgrades while maintaining your global node modules that you may use regularly (like express or react or whatever).  Try it again, and let me know if it doesn't work after 10 minutes.

(edit) the pip installs will not happen on first install (face palm).
how long did you let the script run for?

**Comment by audstanley** [comment]
I'm going to leave this issue open for a few weeks, or until i hear back from you.  Thanks for opening it up, i should put something in the readme about average installation time.

**Comment by ba58smith** [comment]
I'm pretty sure I waited at least 10 minutes the first time (I started it, then left my computer to do something else), and maybe the second time, too. I ended up finding another article about installing the node server and following the steps below, which worked. I know I don't get the version control you've designed, but I don't anticipate doing a lot of different things with node, so hopefully it won't matter. Thanks for the reply, though. Suggestion - while that cursor is sitting there, looking like it's hung up - make it show that something is still happening, if you can.

curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt install nodejs

**Comment by audstanley** [comment]
Closing, since this worked fine on tests i ran with no issues. After running on my pi 3, it looks like your computer (for whatever reason), didn't resolve from nodejs.org.  Must have been an issue on their server end.  Only took 20 seconds on my pi.
