### ISSUE TITLE
You are not running this installer on an ARM based processor.

### ISSUE THREAD

**Issue by Reed-Schimmel** [audstanley/NodeJs-Raspberry-Pi#27]
I get the error "You are not running this installer on an ARM based processor."

Running Raspbian Buster with 64bit kernel
4.19.75-v8+ #1270 SMP PREEMPT Tue Sep 24 18:59:17 BST 2019 aarch64 GNU/Linux

**Comment by audstanley** [comment]
Thanks for the information, what raspberry is aarch64?  I think the pi 4 reports an arm 7.

**Comment by audstanley** [comment]
Ok, so I think aarch64 and arm64 are basically the same (at least in terms of the node binaries). Would you mind trying the installer again on the same architecture and reporting the results? The last push should work. [70e729409b3fd60e46b1c430215a068a02defd2b](https://github.com/audstanley/NodeJs-Raspberry-Pi/commit/70e729409b3fd60e46b1c430215a068a02defd2b)

**Comment by audstanley** [comment]
Ok wow! I didn't know [this](https://www.raspberrypi.org/forums/viewtopic.php?t=250730) was a thing you could do in buster, that super awesome... I'll test this out right now.  That's way cool.

**Comment by audstanley** [comment]
Ok, so the arm64 binaries will not run on the "64bit kernel test mode"  in Rasbian Buster...  They should, but this might be some issue with the OS itself not running a 64bit OS, I'm not sure, so I've at least forced it so that you can update the Pi4 and still run the arm7vl binaries with the node-install script.  This might break other computers (IE an Nvidia TX2), but this script was designed for Raspberry Pis specifically, so I'm going to let other things break so that you can at least run updates on a pi4 running the 64bit kernel mode.
