### ISSUE TITLE
-bash: /usr/bin/node: No such file or directory

### ISSUE THREAD

**Issue by MarcSN311** [audstanley/NodeJs-Raspberry-Pi#31]
I am trying to install NodeJs on a freshly setup Raspberry Pi 1 B running debian bullseye. The NodeJs setup runs fine and ends with `good to go` however `node -v`, `npm` and any other node related command results in `-bash: /usr/bin/node: No such file or directory`. The file does exist, so I am unsure what the problem might be.

```
# ls -la /usr/bin/node
-rwxr-xr-x 1 root root 72828244 Oct 29 11:13 /usr/bin/node
```

**Comment by audstanley** [comment]
The pi 1 is an armv6 architecture - I believe. The binary from this repository is working (for the processor architecture), which is good...

Do you see output of the files being copied into directories (like in the gif)?

I've never used debian bullseye, but I'm willing to bet that the installation is successful... Minus, maybe, an update of the symlinks.

Try running

```bash
/opt/nodejs/bin/node
```

If that launches node, than the symlinks are just not being created over to /usr/bin/node - which is the only part of the code that runs a subprocess CLI command.


One other possibility, is to

```bash
echo $PATH
```

and make sure that /usr/bin is part of the PATH environment variable. If it's not, you can edit /etc/environment so that your PATH to /usr/bin is available system wide.  Another solution would be to edit your .profile in you home directory. 
Be careful with your PATH though, if you break your PATH you can break your OS from working properly - booting even.

If you let me know, what those two commands reveal, I can help with the next step. 😊

Let me know, if you can, what you are seeing.

**Comment by audstanley** [comment]
Oh, I just realized that /usr/bin/node DOES exist - so this tells me that /usr/bin is just not part of the PATH in debian (for some weird reason).

If it was me... I would just edit my /etc/environment to include /usr/bin especially since node sometimes needs to be elevated with root for some libraries. [this might help you decide](https://askubuntu.com/questions/866161/setting-path-variable-in-etc-environment-vs-profile)

**Comment by audstanley** [comment]
So

/etc/environment

If the PATH variable does NOT exist in the /etc/environment file you would edit the PATH this way:

PATH="/usr/bin:$PATH"

If it already exists then you can add /usr/bin to the beginning of the PATH string and add a : as a delimiter between those folders that are listed.  PATH, if you don't know, tells the system, "this is where all the binaries are" and you can list a bunch of directories. Anytime you launch something the OS attempts to find whatever you launched in those directories in the order the folders are listed.

If you update /etc/environment you'll need to restart the machine to see the changes take effect.

**Comment by audstanley** [comment]
okay - try it again.
switch to root and make sure your are running bash, not sh
```bash
su -
```

I checked the PATH on a fresh version of debain 11 [as a VM] and /usr/bin is in the PATH [as it should be].

Once you are root - you can run this without the need for sudo:

```bash
wget -O - https://raw.githubusercontent.com/audstanley/NodeJs-Raspberry-Pi/master/Install-Node.sh | bash;
```

I just rebuilt the binaries using debian 11 since I've been pushing with my main computer [ on bleeding edge so i think i have too new a version of GLIBC for some LTS distros ].  This may resolve other errors that may occur. We'll see what happens next - the GLIBC mismatches have been a challenge that I've been unable to automate - so hopefully this fixes some things.

![image](https://user-images.githubusercontent.com/2934052/139921402-9b76377c-e970-4178-9715-b4f937836e74.png)


I just tested on my main computer running GLIBC version 2.34 and the binaries work just fine - which tells me that it's newer versions of GLIBC are backwards compatible - which is good. This - I think - should also solve [issue #30](https://github.com/audstanley/NodeJs-Raspberry-Pi/issues/30) - I'm going to close both for now.
